/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GestionVente;

import Base_Données.Parameter;
import Base_Données.ResultSetTableModel;
import Base_Données.db_connection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author bouzazi
 */
public class Inventaire extends javax.swing.JFrame {

    /**
     * Creates new form utilisateur
     */
    ResultSet rs;
    db_connection db;
    public Inventaire() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
 tableP();
   DateN();
    }
     public void DateN() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        TempN.setText(jam.format(s));
        dateN.setText(tgl.format(s));}
     public void table() {
        String tab[] = {"id","dateInventaire","CodeProduitI","referenceI","Qte"};
  
        rs = db.querySelect(tab, "inventaire");
        tbl_prod.setModel(new ResultSetTableModel(rs));
    }
       public void tableP() {
        String tab[] = {"code_produit","reference","stock"};
  
        rs = db.querySelect(tab, "produit");
        tabP.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
        txtid.setText("");
        txtref.setText("");
      
        txtsto.setText("");}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtref = new javax.swing.JTextField();
        txtsto = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        TempN = new javax.swing.JLabel();
        dateN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        comrech = new javax.swing.JComboBox();
        txtrech = new javax.swing.JTextField();
        Recherche = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Actualiser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MJS = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(50, 50));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1430, 950));
        setSize(new java.awt.Dimension(950, 950));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 900));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Date inventaire");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 20, 130, 27);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Reference   ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 110, 120, 27);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Quantité");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 160, 90, 27);
        jPanel2.add(txtid);
        txtid.setBounds(170, 70, 380, 30);
        jPanel2.add(txtref);
        txtref.setBounds(170, 110, 380, 30);

        txtsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstoActionPerformed(evt);
            }
        });
        jPanel2.add(txtsto);
        txtsto.setBounds(170, 160, 380, 30);
        jPanel2.add(jXDatePicker1);
        jXDatePicker1.setBounds(174, 20, 290, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Code produit  ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 70, 130, 27);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 260, 570, 200);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tbl_prod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_prod.setForeground(new java.awt.Color(0, 0, 102));
        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "code_produit", "reference", "Quantité "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_prod.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prod);
        if (tbl_prod.getColumnModel().getColumnCount() > 0) {
            tbl_prod.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(40, 450, 740, 480);

        jPanel4.setBackground(new java.awt.Color(51, 0, 255));

        TempN.setBackground(new java.awt.Color(51, 0, 255));
        TempN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TempN.setForeground(new java.awt.Color(255, 255, 255));
        TempN.setText("TempN");

        dateN.setBackground(new java.awt.Color(51, 0, 255));
        dateN.setForeground(new java.awt.Color(255, 255, 255));
        dateN.setText("DateN");

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.JPG"))); // NOI18N

        Retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.JPG"))); // NOI18N
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inventaire des stocks");

        jButton8.setBackground(new java.awt.Color(51, 0, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TempN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(dateN)
                        .addGap(19, 19, 19)
                        .addComponent(TempN)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1490, 120);

        comrech.setForeground(new java.awt.Color(0, 0, 204));
        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "code_produit", "reference", "Date", "stock" }));
        jPanel1.add(comrech);
        comrech.setBounds(30, 170, 160, 40);
        jPanel1.add(txtrech);
        txtrech.setBounds(200, 170, 300, 40);

        Recherche.setBackground(new java.awt.Color(255, 255, 255));
        Recherche.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Recherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });
        jPanel1.add(Recherche);
        Recherche.setBounds(510, 170, 50, 40);

        Ajouter.setBackground(new java.awt.Color(255, 255, 255));
        Ajouter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A.png"))); // NOI18N
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });
        jPanel1.add(Ajouter);
        Ajouter.setBounds(680, 190, 40, 40);

        Modifier.setBackground(new java.awt.Color(255, 255, 255));
        Modifier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/M.jpg"))); // NOI18N
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        jPanel1.add(Modifier);
        Modifier.setBounds(680, 240, 40, 40);

        Supprimer.setBackground(new java.awt.Color(255, 255, 255));
        Supprimer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/S.png"))); // NOI18N
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(Supprimer);
        Supprimer.setBounds(680, 290, 40, 40);

        Actualiser.setBackground(new java.awt.Color(255, 255, 255));
        Actualiser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AC.jpg"))); // NOI18N
        Actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualiserActionPerformed(evt);
            }
        });
        jPanel1.add(Actualiser);
        Actualiser.setBounds(680, 340, 40, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/im.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 390, 70, 60);

        MJS.setBackground(new java.awt.Color(0, 0, 153));
        MJS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MJS.setForeground(new java.awt.Color(255, 255, 255));
        MJS.setText("Mise a jour stock");
        MJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MJSActionPerformed(evt);
            }
        });
        jPanel1.add(MJS);
        MJS.setBounds(910, 270, 270, 60);

        tabP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabP.setForeground(new java.awt.Color(0, 0, 102));
        tabP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "code_produit", "reference", "Quantité "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabP.setGridColor(new java.awt.Color(255, 255, 255));
        tabP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabP);
        if (tabP.getColumnModel().getColumnCount() > 0) {
            tabP.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(810, 460, 580, 402);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1530, 930);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        if (txtrech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        } else {
            if (comrech.getSelectedItem().equals("code_produit")) {
                rs = db.querySelectAll("inventaire", "CodeProduitI LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("reference")) {
                rs = db.querySelectAll("inventaire", "referenceI LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("Date")) {
                rs = db.querySelectAll("inventaire", "dateInventaire LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));

            } else if (comrech.getSelectedItem().equals("Qte")) {
                rs = db.querySelectAll("inventaire", "Qte LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));

            }
        }
    }//GEN-LAST:event_RechercheActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Principale p=new Principale();
        p.setVisible(true);
    }//GEN-LAST:event_RetourActionPerformed

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked
        txtid.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 2)));
        txtref.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3)));
       
          txtsto.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(),4)));
      
    }//GEN-LAST:event_tbl_prodMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_produit","root","");
            JasperDesign jdesign = JRXmlLoader.load("B:\\1ere TIC\\JavaProjet\\Gestion_Vente\\Gestion_Vente\\src\\GestionVente\\Inventaire.jrxml");
               SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
                formater.format(jXDatePicker1.getDate());
            String query ="select * from inventaire,produit where (produit.code_produit=inventaire.CodeProduitI)and inventaire.dateInventaire='" + formater.format(jXDatePicker1.getDate()) + "'";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);

            jdesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null,con);

            JasperViewer.viewReport(jprint);

            // TODO add your handling code here:
        } catch (JRException ex) {
       
            Logger.getLogger(Inventaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {

            Logger.getLogger(Inventaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           
            Logger.getLogger(Inventaire.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualiserActionPerformed
        actualiser(); table();        // TODO add your handling code here:
    }//GEN-LAST:event_ActualiserActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        if (txtsto.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complete");
        } else {
             SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
                formater.format(jXDatePicker1.getDate());
            String[] colon = {"dateInventaire","CodeProduitI","referenceI","Qte"};
            String[]  inf = {formater.format(jXDatePicker1.getDate()),txtid.getText(), txtref.getText(),txtsto.getText()};
            String id = String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("inventaire", colon, inf, "id='" + id + "'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_ModifierActionPerformed

    private void txtstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        if (txtid.getText().equals("") || txtref.getText().equals("") || txtsto.getText().equals("")
        ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complete");
        } else {
             SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
                formater.format(jXDatePicker1.getDate());
            String[] colon = {"dateInventaire","CodeProduitI","referenceI","Qte"};
             String[]  inf = {formater.format(jXDatePicker1.getDate()),txtid.getText(), txtref.getText(),txtsto.getText()};
            System.out.println(db.queryInsert("inventaire", colon, inf));
            table();
            actualiser();
        }
    }//GEN-LAST:event_AjouterActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        String id = String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux suuprimer", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("inventaire", "id=" + id);
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_SupprimerActionPerformed

    private void MJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MJSActionPerformed
        try {
          
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_produit","root","");
           
            String query =" UPDATE produit,inventaire\n" +
                               "SET produit.stock = inventaire.Qte\n" +
                               "WHERE produit.code_produit = inventaire.CodeProduitI";
            Statement stmt = con.createStatement();
            int  résultats = stmt.executeUpdate(query);
            
            /*pour select
                ResultSet  résultats = stmt.executeQuery(query);*/
          
             JOptionPane.showMessageDialog(this, "La mise à jour a réussi");
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inventaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Inventaire.class.getName()).log(Level.SEVERE, null, ex);
        }
           
          

    
            
           
            
            
    }//GEN-LAST:event_MJSActionPerformed

    private void tabPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPMouseClicked
 Connection con;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualiser;
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton MJS;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Recherche;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Supprimer;
    public static javax.swing.JLabel TempN;
    private javax.swing.JComboBox comrech;
    public static javax.swing.JLabel dateN;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTable tabP;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtrech;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
